auto

diff --git a/bin/dangling-rm b/bin/dangling-rm
--- a/bin/dangling-rm
+++ b/bin/dangling-rm
@@ -3,9 +3,42 @@
 # Find dangling symlinks
 #
 
-tmp="$(mktemp)"
-dangling "$@"  > "${tmp}"
-while read -r link; do
-  rm "${link}"  && Ok "${0##*/}" "${link}: removed"
-done < "${tmp}"
+#######################################
+# show usage
+# Arguments:
+#   1
+#######################################
+help() {
+  case "$1" in
+    -h|--help|help) rc=0 ;;
+    -*)
+      >&2 die "$1: invalid option/argument"
+      >&2 echo
+      ;;
+    *) return ;;
+  esac
 
+  >&2 cat <<EOF
+usage: ${0##*/}  [dir]
+   or: ${0##*/} [-h|--help|help]
+
+remove dangling symlinks in directory (default: cwd)
+
+Commands:
+   -h, --help, help     display this help and exit.
+EOF
+  exit "${rc:-1}"
+}
+
+
+main() {
+  help "$@"
+
+  tmp="$(mktemp)"
+  dangling "$@" >"${tmp}"
+  while read -r link; do
+    rm "${link}" && Ok "${0##*/}" "${link}: removed"
+  done <"${tmp}"
+}
+
+main "$@"
diff --git a/bin/home b/bin/home
--- a/bin/home
+++ b/bin/home
@@ -1,13 +1,46 @@
 #!/bin/sh
+
 #
 # User HOME (because of sudoers !env_reset)
 
+
+#######################################
+# show users home
+# Arguments:
+#   1
+#######################################
+help() {
+  case "$1" in
+    -h|--help|help) rc=0 ;;
+    -*) RETURN="return" die "$1: invalid option/argument\n" ;;
+    *) return 0 ;;
+  esac
+
+  >&2 cat <<EOF
+usage: ${0##*/} [user]
+   or: ${0##*/} -h|--help|help
+
+show user's home, default $HOME
+
+Arguments:
+  user            user name (default: $USER)
+
+Commands:
+   -h, --help, help   display this help and exit.
+EOF
+  exit "${rc:-1}"
+}
+
 #######################################
 # get user home
+# eval echo ~"${1:-$(user)}"
 # Arguments:
 #  user     default $GIT or $USER
 #######################################
 # shellcheck disable=SC2016
-home() { ${SUDO:+${SUDO} -u} "${1-${GIT}}" sh -c 'echo "${HOME}"'; }
+main() {
+  help "$@"
+  ${SUDO:+${SUDO} -u} "${1-${USER}}" sh -c 'echo "${HOME}"'; }
 
-eval echo ~"${1:-$(user)}"
+
+main "$@"
diff --git a/bin/usernames b/bin/usernames
--- a/bin/usernames
+++ b/bin/usernames
@@ -1,10 +1,53 @@
 #!/bin/sh
 
-if $MACOS; then
-  dscl . list /Users | grep -v '^_' | grep -vE "daemon|nobody"
-else
-## get UID limit ##
-  l=$(grep "^UID_MIN" /etc/login.defs)
-  ## use awk to print if UID >= $UID_LIMIT ##
-  awk -F':' -v "limit=${l##UID_MIN}" '{ if ( $3 >= limit ) print $1}' /etc/passwd
-fi
+
+#######################################
+# show usage
+# Arguments:
+#   1
+#######################################
+help() {
+  test $# -gt 0 || return 0
+
+  case "$1" in
+    -h|--help|help) rc=0 ;;
+    -*)
+      >&2 die "$1: invalid option/argument"
+      >&2 echo
+      ;;
+    *) return ;;
+  esac
+
+  >&2 cat <<EOF
+usage: ${0##*/}
+   or: ${0##*/} [-h|--help|help]
+
+list users who can log in into the system
+
+Commands:
+   -h, --help, help     display this help and exit.
+EOF
+  exit "${rc:-1}"
+}
+
+
+#######################################
+#list users who can log into the system
+# Arguments:
+#  None
+#######################################
+
+main()  {
+  help "$@"
+
+  if $MACOS; then
+    dscl . list /Users | grep -v '^_' | grep -vE "daemon|nobody"
+  else
+    ## get UID limit ##
+    l=$(grep "^UID_MIN" /etc/login.defs)
+    ## use awk to print if UID >= $UID_LIMIT ##
+    echo root && awk -F':' -v "limit=${l##UID_MIN}" '{ if ( $3 >= limit ) print $1}' /etc/passwd | grep -vE "nobody"
+  fi
+}
+
+main "$@"
